/* eslint-disable */
// @ts-nocheck
/* prettier-ignore */
/* oxlint-disable */
// biome-ignore lint: disable
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

export {}

declare module "vue-router" {
  type RouteNamedMap = import("vue-router/auto-routes").RouteNamedMap;

  export interface TypesConfig {
    RouteNamedMap: RouteNamedMap;
  }
}

declare module "vue-router/auto-routes" {
  import type { RouteParamsRawGeneric, RouteParamsGeneric, RouteMeta, RouteRecordInfo, ParamValue, ParamValueZeroOrOne } from "vue-router";

  /**
   * route named map
  */
  export interface RouteNamedMap {
    "Root": RouteRecordInfo<"Root", "/", Record<never, never>, Record<never, never>>;
    "NotFound": RouteRecordInfo<"NotFound", "/:pathMatch(.*)*", Record<never, never>, Record<never, never>>;
    "_builtin403": RouteRecordInfo<"_builtin403", "/_builtin/403", Record<never, never>, Record<never, never>>;
    "_builtin404": RouteRecordInfo<"_builtin404", "/_builtin/404", Record<never, never>, Record<never, never>>;
    "_builtin500": RouteRecordInfo<"_builtin500", "/_builtin/500", Record<never, never>, Record<never, never>>;
    "_builtinIframePageUrl": RouteRecordInfo<"_builtinIframePageUrl", "/_builtin/iframe-page/:url", { url: ParamValue<true> }, { url: ParamValue<false> }>;
    "_builtinLogin": RouteRecordInfo<"_builtinLogin", "/_builtin/login", Record<never, never>, Record<never, never>>;
    "About": RouteRecordInfo<"About", "/about", Record<never, never>, Record<never, never>>;
    "Home": RouteRecordInfo<"Home", "/home", Record<never, never>, Record<never, never>>;
    "ManageErrorCode": RouteRecordInfo<"ManageErrorCode", "/manage/error/code", Record<never, never>, Record<never, never>>;
    "ManageMenu": RouteRecordInfo<"ManageMenu", "/manage/menu", Record<never, never>, Record<never, never>>;
    "ManageRole": RouteRecordInfo<"ManageRole", "/manage/role", Record<never, never>, Record<never, never>>;
    "ManageUser": RouteRecordInfo<"ManageUser", "/manage/user", Record<never, never>, Record<never, never>>;
    "ManageUserDetailId": RouteRecordInfo<"ManageUserDetailId", "/manage/user-detail/:id", { id: ParamValue<true> }, { id: ParamValue<false> }>;
    "MultiMenuFirstChild": RouteRecordInfo<"MultiMenuFirstChild", "/multi-menu/first_child", Record<never, never>, Record<never, never>>;
    "MultiMenuSecondChildHome": RouteRecordInfo<"MultiMenuSecondChildHome", "/multi-menu/second_child_home", Record<never, never>, Record<never, never>>;
    "UserCenter": RouteRecordInfo<"UserCenter", "/user-center", Record<never, never>, Record<never, never>>
  }
}
